language: ruby
rvm:
  - 2.4.1
before_script:
  - chmod +x ./scripts/cibuild.sh
script: ./scripts/cibuild.sh
# branch whitelist, only for GitHub Pages
branches:
  only:
  - dev     # test the gh-pages branch
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler

after_success:
  - chmod +x ./scripts/cideploy.sh
  - ./scripts/cideploy.sh

notifications:
  email: yan.gerasimuk@yandex.ru