language: ruby
rvm:
  - 2.4.1
branches:
  only:
  - dev     # test the gh-pages branch
sudo: false # route your build to the container-based infrastructure for a faster build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache: bundler
notifications:
  email: yan.gerasimuk@yandex.ru
  
before_script:
  - chmod +x ./_scripts/cibuild.sh

script: ./_scripts/cibuild.sh
# branch whitelist, only for GitHub Pages

after_success:
  - chmod +x ./_scripts/cideploy.sh
  - ./_scripts/cideploy.sh

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep-history: true
#  on:
#    branch: dev