title: <yangerasimuk.ru/>
email: yan.gerasimuk@yandex.ru
author: Ян Гeрaсимук
copyright: "&copy; 2018 Ян Гeрaсимук"
description: > # this means to ignore newlines until "baseurl:"
  Заметки ни о чём :)
baseurl: "" # the subpath of your site, e.g. /blog
url: http://yangerasimuk.ru # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year-:month-:day-:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - docs
  - vendor
  - make.sh
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md 
  - .bundle
  - .nojekyll
  - .gitignore
  
sass:
    sass_dir: _sass
    style: compressed
paginate: 10
paginate_path: page/:num"
destination: docs
# Integration
yandex_verification: d8be58cfab9dd6e8 

#theme: minima
#bootstrap:
 # assets: true